# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

import sys

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pb2
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='rpc.proto',
    package='filesyncrpc',
    syntax='proto3',
    serialized_pb=_b('\n\trpc.proto\x12\x0b\x66ilesyncrpc\"\x1c\n\x08\x43hecksum\x12\x10\n\x08\x63hecksum\x18\x01 \x01(\t\"{\n\x04\x46ile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x08\x63hecksum\x18\x02 \x01(\x0b\x32\x15.filesyncrpc.Checksum\x12\x11\n\tblocksize\x18\x03 \x01(\r\x12)\n\nblockcsums\x18\x04 \x03(\x0b\x32\x15.filesyncrpc.Checksum\"`\n\x05\x42lock\x12\x0e\n\x06number\x18\x01 \x01(\x04\x12\'\n\x08\x63hecksum\x18\x02 \x01(\x0b\x32\x15.filesyncrpc.Checksum\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x10\n\x08\x65xisting\x18\x04 \x01(\x04\"b\n\x05Patch\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x08\x63hecksum\x18\x02 \x01(\x0b\x32\x15.filesyncrpc.Checksum\x12\"\n\x06\x62locks\x18\x03 \x03(\x0b\x32\x12.filesyncrpc.Block2B\n\x0b\x46ileSyncRpc\x12\x33\n\x08GetPatch\x12\x11.filesyncrpc.File\x1a\x12.filesyncrpc.Patch\"\x00\x62\x06proto3')  # NOQA
)


_CHECKSUM = _descriptor.Descriptor(
    name='Checksum',
    full_name='filesyncrpc.Checksum',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='checksum', full_name='filesyncrpc.Checksum.checksum', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=26,
    serialized_end=54,
)


_FILE = _descriptor.Descriptor(
    name='File',
    full_name='filesyncrpc.File',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='name', full_name='filesyncrpc.File.name', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='checksum', full_name='filesyncrpc.File.checksum', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='blocksize', full_name='filesyncrpc.File.blocksize', index=2,
            number=3, type=13, cpp_type=3, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='blockcsums', full_name='filesyncrpc.File.blockcsums', index=3,
            number=4, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=56,
    serialized_end=179,
)


_BLOCK = _descriptor.Descriptor(
    name='Block',
    full_name='filesyncrpc.Block',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='number', full_name='filesyncrpc.Block.number', index=0,
            number=1, type=4, cpp_type=4, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='checksum', full_name='filesyncrpc.Block.checksum', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='data', full_name='filesyncrpc.Block.data', index=2,
            number=3, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=_b(""),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='existing', full_name='filesyncrpc.Block.existing', index=3,
            number=4, type=4, cpp_type=4, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=181,
    serialized_end=277,
)


_PATCH = _descriptor.Descriptor(
    name='Patch',
    full_name='filesyncrpc.Patch',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='name', full_name='filesyncrpc.Patch.name', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='checksum', full_name='filesyncrpc.Patch.checksum', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='blocks', full_name='filesyncrpc.Patch.blocks', index=2,
            number=3, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=279,
    serialized_end=377,
)

_FILE.fields_by_name['checksum'].message_type = _CHECKSUM
_FILE.fields_by_name['blockcsums'].message_type = _CHECKSUM
_BLOCK.fields_by_name['checksum'].message_type = _CHECKSUM
_PATCH.fields_by_name['checksum'].message_type = _CHECKSUM
_PATCH.fields_by_name['blocks'].message_type = _BLOCK
DESCRIPTOR.message_types_by_name['Checksum'] = _CHECKSUM
DESCRIPTOR.message_types_by_name['File'] = _FILE
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
DESCRIPTOR.message_types_by_name['Patch'] = _PATCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Checksum = _reflection.GeneratedProtocolMessageType('Checksum', (_message.Message,), dict(
    DESCRIPTOR=_CHECKSUM,
    __module__='rpc_pb2'
    # @@protoc_insertion_point(class_scope:filesyncrpc.Checksum)
))
_sym_db.RegisterMessage(Checksum)

File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), dict(
    DESCRIPTOR=_FILE,
    __module__='rpc_pb2'
    # @@protoc_insertion_point(class_scope:filesyncrpc.File)
))
_sym_db.RegisterMessage(File)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), dict(
    DESCRIPTOR=_BLOCK,
    __module__='rpc_pb2'
    # @@protoc_insertion_point(class_scope:filesyncrpc.Block)
))
_sym_db.RegisterMessage(Block)

Patch = _reflection.GeneratedProtocolMessageType('Patch', (_message.Message,), dict(
    DESCRIPTOR=_PATCH,
    __module__='rpc_pb2'
    # @@protoc_insertion_point(class_scope:filesyncrpc.Patch)
))
_sym_db.RegisterMessage(Patch)


_FILESYNCRPC = _descriptor.ServiceDescriptor(
    name='FileSyncRpc',
    full_name='filesyncrpc.FileSyncRpc',
    file=DESCRIPTOR,
    index=0,
    options=None,
    serialized_start=379,
    serialized_end=445,
    methods=[
        _descriptor.MethodDescriptor(
            name='GetPatch',
            full_name='filesyncrpc.FileSyncRpc.GetPatch',
            index=0,
            containing_service=None,
            input_type=_FILE,
            output_type=_PATCH,
            options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_FILESYNCRPC)

DESCRIPTOR.services_by_name['FileSyncRpc'] = _FILESYNCRPC

# @@protoc_insertion_point(module_scope)
